### ISSUE TITLE
com.dexcom.cgm.region1.mmol-patched.apk crashes when sending data to AAPS

### ISSUE THREAD

**Issue by efrost123** [dexcomapp/dexcomapp#19]
Hello,

The issue might be related to https://github.com/dexcomapp/dexcomapp/issues/16 

When dexcom patched app sends data to AAPM it crushes with exception (see below).
After reinstalling Dexcom patched app it seems to be working fine for some time, until number of glucose values and meter data is not too big to be broadcasted.
The problem is in procedure ExternalAppCGMCallback.evCgmData that gathers data for last day, packs it to Bundle and tries to sendBroadcast.

I have two suggestions:
1. Fast fix: send data for smaller period of time. 4 hours?
2. Proper fix: control size of the parcel and send data in a few broadcasts.
This should properly work for AAPS because there are no assumptions about data received in one broadcast (e.g. that one broadcast contains all data up to current moment), so it will process everything correctly.

Exception:
2019-08-19 19:28:41.643 5917-5957/com.dexcom.cgm.region1.mmol E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1319380)
2019-08-19 19:28:41.647 5917-5957/com.dexcom.cgm.region1.mmol E/AndroidRuntime: FATAL EXCEPTION: TransmitterMediatorPublisher
    Process: com.dexcom.cgm.region1.mmol, PID: 5917
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1319380 bytes
        at android.app.ContextImpl.sendBroadcast(ContextImpl.java:965)
        at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:442)
        at com.dexcom.cgm.ExternalAppCGMCallback.evCgmData(ExternalAppCGMCallback.java:65)
        at com.dexcom.cgm.component_provider.e.sendDataUpdate(Unknown Source:23)
        at com.dexcom.cgm.component_provider.e.access$000(Unknown Source:0)
        at com.dexcom.cgm.component_provider.f.evCgmData(Unknown Source:2)
        at com.dexcom.cgm.b.j.updateListenersOnNewData(Unknown Source:23)
        at com.dexcom.cgm.b.j.receiveConnectionCompleteData(Unknown Source:77)
        at com.dexcom.cgm.b.j.syncEvConnectionSuccess(Unknown Source:59)
        at com.dexcom.cgm.b.j.access$100(Unknown Source:0)
        at com.dexcom.cgm.b.l.evConnectionSuccess(Unknown Source:2)
        at com.dexcom.cgm.test.h.evConnectionSuccess(Unknown Source:44)
        at com.dexcom.cgm.tx.mediator.bq.run(Unknown Source:527)
        at com.dexcom.cgm.tx.mediator.bu.run(Unknown Source:13)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1319380 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:761)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:5022)
        at android.app.ContextImpl.sendBroadcast(ContextImpl.java:960)
        at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:442) 
        at com.dexcom.cgm.ExternalAppCGMCallback.evCgmData(ExternalAppCGMCallback.java:65) 
        at com.dexcom.cgm.component_provider.e.sendDataUpdate(Unknown Source:23) 
        at com.dexcom.cgm.component_provider.e.access$000(Unknown Source:0) 
        at com.dexcom.cgm.component_provider.f.evCgmData(Unknown Source:2) 
        at com.dexcom.cgm.b.j.updateListenersOnNewData(Unknown Source:23) 
        at com.dexcom.cgm.b.j.receiveConnectionCompleteData(Unknown Source:77) 
        at com.dexcom.cgm.b.j.syncEvConnectionSuccess(Unknown Source:59) 
        at com.dexcom.cgm.b.j.access$100(Unknown Source:0) 
        at com.dexcom.cgm.b.l.evConnectionSuccess(Unknown Source:2) 
        at com.dexcom.cgm.test.h.evConnectionSuccess(Unknown Source:44) 
        at com.dexcom.cgm.tx.mediator.bq.run(Unknown Source:527) 
        at com.dexcom.cgm.tx.mediator.bu.run(Unknown Source:13) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by T1Diab** [comment]
Started getting these crashes last night as well.

**Comment by twain47** [comment]
@efrost123 Can I ask where you found these logs?

**Comment by efrost123** [comment]
Connected phone to my comp with adb and android studio and was waiting for any exception before dexcom process crashed.

**Comment by twain47** [comment]
Thanks - I'll try that next time.

**Comment by twain47** [comment]
I think I may have found the cause. Decompiling ExternalAppCGMCallback I see:

h hVar = new h(TimeUnit.MILLISECONDS.toSeconds(TimeUnit.MILLISECONDS.toSeconds(currentTimeMillis - TimeUnit.HOURS.toMillis(1))));

where the time is converted to milliseconds twice.

**Comment by twain47** [comment]
I've patched out the above issue and have now been running for 14 days without problem (longer than any time previously). Can probably confirm that fixing the above resolves the issue.

**Comment by radu-neacsu** [comment]
up!
